name: Trigger Workflow 2

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at 00:00 UTC
    - cron: '0 6 * * *'  # Every day at 06:00 UTC
    - cron: '0 12 * * *' # Every day at 12:00 UTC
    - cron: '0 18 * * *' # Every day at 18:00 UTC

jobs:
  trigger-workflow-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify your Python version

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run workflow trigger script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: ${{ secrets.REPO_OWNER }}
        REPO_NAME: ${{ secrets.REPO_NAME }}
        WORKFLOW_ID: ${{ secrets.WORKFLOW_ID }}
      run: |
        python Main.py
